### ISSUE TITLE
BrowserModule has already been loaded

### ISSUE THREAD

**Issue by yuanye2005king** [mokeyish/ngx-property-grid#21]
ngx-property-grid is useful to my angular-cli project, but when I installed this module, I got a BrowserModule error. I think Your index.ts in the property-grid imports the BrowserAnimationsModule that should be remove.

**Comment by MansuriNiyamat** [comment]
Hey I am also facing same issue. could anyone please make changes and create pull request

**Comment by mokeyish** [comment]
@yuanye2005king Can you provide the example project code？

**Comment by MansuriNiyamat** [comment]
I am following process steps same as given on main page. facing error 

`Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.`

I am importing PropertyGridModule in my sub module of project.  taking simple sample from ngx-property-grid. 

mansuriniyamat.tech@gmail.com  / skype : nimu19931

**Comment by MansuriNiyamat** [comment]
using this versions
`    "ngx-property-grid": "^1.0.21",
    "ngx-template": "^1.0.5",`

in https://stackblitz.com/edit/angular-veuf4i  it is working correct with some downgraded versions. so what should be problem, or need to change anything.

**Comment by mokeyish** [comment]
I will solve it later.😬

**Comment by MansuriNiyamat** [comment]
yes Thanks, but could you provide suggestion so I can solve it. it is emergency.

**Comment by mokeyish** [comment]
@MansuriNiyamat How to reproduce it?

**Comment by mokeyish** [comment]
fixed in #22
